-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES 

FROM REST_INFO AS R
INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS I
ON R.FOOD_TYPE = I.FOOD_TYPE
AND R.FAVORITES = I.FAVORITES 

ORDER BY FOOD_TYPE DESC;