-- 코드를 작성해주세요

SELECT I.ID, N.FISH_NAME, I.LENGTH

FROM FISH_INFO AS I 

INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE 
) AS S

ON S.FISH_TYPE = I.FISH_TYPE
AND S.MAX_LENGTH = I.LENGTH 

INNER JOIN FISH_NAME_INFO AS N

ON I.FISH_TYPE = N.FISH_TYPE

ORDER BY I.ID ASC;
